### ISSUE TITLE
Edad

### ISSUE THREAD

**Issue by JayRD01** [JayRD01/gg#1]
#Encoding: utf-8
edad = 18

if edad >= 0 and < 18:
	print ('Eres un niño papu')
elif edad>= 20 and < 28:
	print ('Eres un joven')
elif edad>= 29 and <60:
	print ('Eres un adulto')
else:
	print ('Eres de la tercera edad. Ya tu tiene que morite mi loco')

**Comment by JaimeCabrera** [comment]
noob ✌️

**Comment by JayRD01** [comment]
khé berga :'v

**Comment by JaimeCabrera** [comment]
ya el codigo asi te debe quedar en python es muy importante la identacion`#Encoding: utf-8
edad = 18
if edad >= 0 and edad < 18:
    print ('Eres un niÃ±o papu')
elif edad>= 20 and edad < 28:
    print ('Eres un joven')
elif edad>= 29 and edad <60:
    print ('Eres un adulto')
else:
    print ('Eres de la tercera edad. Ya tu tiene que morite mi loco')`

**Comment by JaimeCabrera** [comment]
#Encoding: utf-8
edad = 18
if edad >= 0 and edad < 18:
    print ('Eres un niÃ±o papu')
elif edad>= 20 and edad < 28:
    print ('Eres un joven')
elif edad>= 29 and edad <60:
    print ('Eres un adulto')
else:
    print ('Eres de la tercera edad. Ya tu tiene que morite mi loco')

**Comment by JaimeCabrera** [comment]
`#Encoding: utf-8
edad = 18
if edad >= 0 and edad < 18:
    print ('Eres un niÃ±o papu')
elif edad>= 20 and edad < 28:
    print ('Eres un joven')
elif edad>= 29 and edad <60:
    print ('Eres un adulto')
else:
    print ('Eres de la tercera edad. Ya tu tiene que morite mi loco')`
